In [1]:
import pandas as pd
data = pd.read_csv('/content/data_with_ner_pos_vocabcount.csv')

In [2]:
data.columns

Index(['problem', 'level', 'no_of_equations', 'modified_problem',
       'sentence_count', 'word_count', 'words_per_sentence',
       'average_word_length', 'large_words', 'has_repeated_large_words',
       'CARDINAL', 'DATE', 'EVENT', 'FAC', 'GPE', 'LANGUAGE', 'LAW', 'LOC',
       'MONEY', 'NORP', 'ORDINAL', 'ORG', 'PERCENT', 'PERSON', 'PRODUCT',
       'QUANTITY', 'TIME', 'WORK_OF_ART', 'ADJ', 'ADP', 'ADV', 'AUX', 'CONJ',
       'CCONJ', 'DET', 'INTJ', 'NOUN', 'NUM', 'PART', 'PRON', 'PROPN', 'PUNCT',
       'SCONJ', 'SYM', 'VERB', 'X', 'math_vocab_count'],
      dtype='object')

In [25]:
data.drop(columns = ['CARDINAL', 'DATE', 'EVENT', 'FAC', 'GPE', 'LANGUAGE', 'LAW', 'LOC',
       'MONEY', 'NORP', 'ORDINAL', 'ORG', 'PRODUCT', 'WORK_OF_ART'], inplace = True)

In [3]:
data.drop(columns = ['problem', 'modified_problem'], inplace = True)

In [4]:
data.head()

,level,no_of_equations,sentence_count,word_count,words_per_sentence,average_word_length,large_words,has_repeated_large_words,CARDINAL,DATE,...,NUM,PART,PRON,PROPN,PUNCT,SCONJ,SYM,VERB,X,math_vocab_count
0,Level 2,0,2,41,20,4,2,True,1,0,...,3,2,0,0,5,1,0,5,0,20
1,Level 5,4,3,100,33,4,9,True,6,0,...,6,7,9,1,12,3,0,13,0,46
2,Level 2,1,1,22,22,4,3,False,0,0,...,0,0,1,0,2,0,0,0,0,9
3,Level 5,2,1,10,10,4,2,False,0,0,...,0,0,1,0,2,1,0,0,0,4
4,Level 4,0,3,45,15,4,2,True,1,0,...,1,0,0,9,5,5,0,7,0,26

In [5]:
for i in range(data.shape[0]):
  data['level'][i] = data['level'][i][6]

<ipython-input-5-992cb1e16ca9>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data['level'][i] = data['level'][i][6]

In [6]:
data.head()

,level,no_of_equations,sentence_count,word_count,words_per_sentence,average_word_length,large_words,has_repeated_large_words,CARDINAL,DATE,...,NUM,PART,PRON,PROPN,PUNCT,SCONJ,SYM,VERB,X,math_vocab_count
0,2,0,2,41,20,4,2,True,1,0,...,3,2,0,0,5,1,0,5,0,20
1,5,4,3,100,33,4,9,True,6,0,...,6,7,9,1,12,3,0,13,0,46
2,2,1,1,22,22,4,3,False,0,0,...,0,0,1,0,2,0,0,0,0,9
3,5,2,1,10,10,4,2,False,0,0,...,0,0,1,0,2,1,0,0,0,4
4,4,0,3,45,15,4,2,True,1,0,...,1,0,0,9,5,5,0,7,0,26

In [26]:
X = data.drop(columns = ['level'])
y = data['level']

In [27]:
y.value_counts()

5    393
4    373
3    372
2    321
1    175
Name: level, dtype: int64

In [28]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 2, stratify = y)

In [29]:
from sklearn.metrics import classification_report, confusion_matrix

def evaluation(y_train_pred, y_test_pred, y_train, y_test):
  print("train_evaluation:\n")
  print(classification_report(y_train_pred, y_train))
  print(confusion_matrix(y_train_pred, y_train))
  print("\ntest_evaluation:\n")
  print(classification_report(y_test_pred, y_test))
  print(confusion_matrix(y_test_pred, y_test))

In [30]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(class_weight='balanced')
dt.fit(X_train, y_train)
y_test_pred = dt.predict(X_test)
y_train_pred = dt.predict(X_train)
evaluation(y_train_pred, y_test_pred, y_train, y_test)

train_evaluation:

              precision    recall  f1-score   support

           1       0.91      0.75      0.82       169
           2       0.83      0.84      0.84       253
           3       0.89      0.84      0.87       316
           4       0.86      0.96      0.91       267
           5       0.94      0.98      0.96       302

    accuracy                           0.89      1307
   macro avg       0.89      0.87      0.88      1307
weighted avg       0.89      0.89      0.88      1307

[[127  27   6   6   3]
 [  3 213  21  13   3]
 [ 10  15 266  19   6]
 [  0   0   3 257   7]
 [  0   2   2   3 295]]

test_evaluation:

              precision    recall  f1-score   support

           1       0.37      0.30      0.33        43
           2       0.30      0.35      0.32        55
           3       0.30      0.27      0.28        83
           4       0.39      0.34      0.36        86
           5       0.35      0.47      0.40        60

    accuracy                           0.34       327
   macro avg       0.34      0.34      0.34       327
weighted avg       0.34      0.34      0.34       327

[[13  6  7 12  5]
 [ 7 19 10  7 12]
 [11 20 22 16 14]
 [ 3 10 24 29 20]
 [ 1  9 11 11 28]]

In [31]:
from sklearn.linear_model import LogisticRegression

In [32]:
log=LogisticRegression(class_weight='balanced',max_iter=1000)

In [33]:
log.fit(X_train, y_train)
y_test_pred = log.predict(X_test)
y_train_pred = log.predict(X_train)
evaluation(y_train_pred, y_test_pred, y_train, y_test)

train_evaluation:

              precision    recall  f1-score   support

           1       0.66      0.24      0.36       383
           2       0.22      0.33      0.27       171
           3       0.19      0.27      0.22       211
           4       0.23      0.33      0.27       207
           5       0.53      0.50      0.51       335

    accuracy                           0.34      1307
   macro avg       0.37      0.33      0.32      1307
weighted avg       0.43      0.34      0.35      1307

[[ 93 110  98  51  31]
 [ 13  57  45  39  17]
 [ 18  33  56  60  44]
 [ 11  29  43  68  56]
 [  5  28  56  80 166]]

test_evaluation:

              precision    recall  f1-score   support

           1       0.60      0.24      0.34        88
           2       0.20      0.30      0.24        44
           3       0.19      0.25      0.21        57
           4       0.21      0.30      0.25        53
           5       0.49      0.46      0.48        85

    accuracy                           0.31       327
   macro avg       0.34      0.31      0.30       327
weighted avg       0.38      0.31      0.33       327

[[21 27 18 14  8]
 [ 7 13 13  4  7]
 [ 3  8 14 20 12]
 [ 2  8 14 16 13]
 [ 2  8 15 21 39]]

In [22]:
from sklearn.ensemble import RandomForestClassifier

In [23]:
rfc=RandomForestClassifier(n_estimators=25,class_weight='balanced')

In [34]:
rfc.fit(X_train, y_train)
y_test_pred = rfc.predict(X_test)
y_train_pred = rfc.predict(X_train)
evaluation(y_train_pred, y_test_pred, y_train, y_test)

train_evaluation:

              precision    recall  f1-score   support

           1       0.89      0.76      0.82       165
           2       0.80      0.87      0.83       238
           3       0.90      0.84      0.87       322
           4       0.88      0.94      0.91       278
           5       0.94      0.97      0.96       304

    accuracy                           0.89      1307
   macro avg       0.88      0.87      0.88      1307
weighted avg       0.89      0.89      0.89      1307

[[125  25   6   6   3]
 [  5 206  14  10   3]
 [ 10  21 269  16   6]
 [  0   3   7 262   6]
 [  0   2   2   4 296]]

test_evaluation:

              precision    recall  f1-score   support

           1       0.37      0.37      0.37        35
           2       0.27      0.33      0.30        51
           3       0.30      0.27      0.28        81
           4       0.29      0.33      0.31        67
           5       0.51      0.43      0.47        93

    accuracy                           0.35       327
   macro avg       0.35      0.35      0.35       327
weighted avg       0.36      0.35      0.35       327

[[13  8  4  7  3]
 [ 6 17 15  8  5]
 [10 21 22 17 11]
 [ 2  8 15 22 20]
 [ 4 10 18 21 40]]